### ISSUE TITLE
Kaplan-Meier survival plot

### ISSUE THREAD

**Issue by bartmch** [huangzhii/SALMON#1]
Hi,
Given the trained model and all the variables saved in .pickle format, how can I plot the Kaplan-Meier plot as shown in the article?

I tried multiple combinations but it's impossible to get the same monotonic decreasing curve as reported. Eg.: plotting os_test versus hazard_ratios_lbl_pred_all_test (with or without OS_event_test to censor the data)

Thank you!

**Comment by huangzhii** [comment]
Hi:
Hazard ratios were derived from all five-fold testing sets. I used R library "survival" with overall survival time and event as input. You can check this https://cran.r-project.org/web/packages/survival/survival.pdf or this https://www.datacamp.com/community/tutorials/survival-analysis-R for more information.
Hazards were used to differentiate the predicted OS event (either 1 or 0). 
"The Kaplan-Meier survival curves are generated by dichotomizing all testing patients to low risk and high risk groups via the median hazard ratio." is in the context of our paper.
Thanks!
