### ISSUE TITLE
Old version of tables

### ISSUE THREAD

**Issue by msierk** [huangzhii/SALMON#4]
I'm getting an error trying to install tables, which is required in SALMON.py.  When I try to install it, it requires hdf5 1.8.9, but that version doesn't appear to be available in conda.

mamba install -c ska tables=3.1.1
Encountered problems while solving:
  - nothing provides hdf5 1.8.9 needed by tables-3.1.1-np18py27_1

mamba install hdf5=1.8.9
Encountered problems while solving:
  - nothing provides requested hdf5 1.8.9**

(mamba install hdf5 works fine, installs 1.12.1.  I only see back to 1.10.5 available in Anaconda)

**Comment by huangzhii** [comment]
Thanks for your question. This is a technical issue for setting up the environment in anaconda. I would refer you to the anaconda documentation: https://docs.anaconda.com/anacondaorg/user-guide/. You might want to downgrade your python version to see if hdf5 would work. In addition, the "tables" package is not essential for the experiment.

Zhi
